const profRoutes = {
    signup: "/professional/signup",
    verifyotp: "/professional/verifyotp",
    gsignup: '/professional/gsignup',
    fillProfile: "/professional/fillProfile",
    login: '/professional/login',
    profile: '/professional/profile',
    editProfile: '/professional/editProfile',
    editImage: '/professional/editImage',
    editEmail: '/professional/editEmail',
    verifyEmailOtp: '/professional/verifyEmailOtp',
    editPassword: '/professional/editPassword',
    createPost: '/professional/createPost',
    deletePost: '/professional/deletePost',
    getPosts: '/professional/getPosts',
    getPortraits: '/professional/portraits',
    getProfessionals: '/professional/professionals',
    profDetails: '/professional/profDetails',
    getPostsById: '/professional/postsById',
    likePostbyProf: '/professional/like',
    unlikePostbyProf: '/professional/unlike',
    savePost: '/professional/savePost',
    postComment: '/professional/postComment',
    notifications: '/professional/notifications',
    updateNotification: '/professional/updateNotification',
    requirements: '/professional/requirements',
    subscribe: '/professional/subscribe',
    cancelSubscription: '/professional/cancelSubscription',
    getUserById: '/chat/getUserById',
    getConversations: '/chat/conversations',
    newConversation: '/chat/newConversation',
    newMessage: '/chat/newMessage',
    messages: '/chat/messages',
    forgotPassword: '/professional/forgotPassword',
    verifyOTP: '/professional/verifyOtpForgotPassword',
    changePassword: '/professional/changePassword',
    resendOtp: '/professional/resendOtp',
    logout: '/professional/logout'
}

export default profRoutes;